[package]
name = "camellia"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
comfy-table = "7.1.0"
nom = "7.1.3"
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
rustyline = "13.0.0"
serde = { version = "1.0.193", features = ["derive"] }
